# Generated by Django 3.0.3 on 2020-02-29 11:00

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, verbose_name='NAME')),
                ('phone', models.CharField(help_text='Contact phone number', max_length=13)),
                ('member_car_number', models.CharField(max_length=8, verbose_name="MEMBER's CAR NUMBER")),
                ('registration', models.DateField(auto_now=True)),
                ('expiration', models.DateField(default=datetime.datetime(2020, 3, 29, 11, 0, 28, 225412))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_car_number', models.CharField(max_length=8, verbose_name="USER's CAR NUMBER")),
                ('user_type', models.BooleanField(help_text="'0' is visitor, '1' is member")),
                ('request', models.BooleanField(help_text="'0' is entry, '1' is exit")),
                ('in_time', models.DateTimeField(auto_now_add=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('pee', models.IntegerField(default=0)),
            ],
        ),
    ]
