# Generated by Django 3.0.3 on 2020-02-29 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreSys', '0002_auto_20200229_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='request',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='member',
            name='expiration',
            field=models.DateField(default=datetime.datetime(
                2020, 3, 29, 13, 53, 38, 748088)),
        ),
    ]
