# Generated by Django 3.0.3 on 2020-03-03 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreSys', '0005_auto_20200303_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2020, 4, 3, 2, 9, 9, 758811)),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=False, help_text="'0' is entry, '1' is exit"),
        ),
    ]
