# Generated by Django 3.0.3 on 2020-03-03 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreSys', '0006_auto_20200303_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2020, 4, 3, 11, 18, 47, 452730)),
        ),
    ]
