# Generated by Django 3.0.3 on 2020-03-11 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreSys', '0011_auto_20200306_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 14, 33, 10, 8356)),
        ),
    ]
