# Generated by Django 3.0.3 on 2020-02-29 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2020, 3, 29, 11, 30, 39, 256160)),
        ),
        migrations.AlterField(
            model_name='user',
            name='pee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
